# -*- coding: utf-8 -*-
"""student_performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPPvbx57BHBfEdYAn4KwwGGUpLlqcQKw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings("ignore")


# 1. LOAD DATA

df = pd.read_csv("/content/StudentsPerformance.csv")
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.rename(columns={"race/ethnicity": "ethnicity",
                   "parental_level_of_education": "parental_education",
                   "test_preparation_course": "test_prep"}, inplace=True)


print("STUDENT PERFORMANCE PREDICTION")

print(f"\nDataset shape: {df.shape}")
print(f"Missing values: {df.isnull().sum().sum()}")
print("\nTarget (math score) stats:")
print(df["math_score"].describe().round(2))

# 2. FEATURE ENGINEERING
df["total_score"]    = df["math_score"] + df["reading_score"] + df["writing_score"]
df["avg_score"]      = df["total_score"] / 3
df["reading_writing_avg"] = (df["reading_score"] + df["writing_score"]) / 2
# 3. ENCODING
cat_cols = ["gender", "ethnicity", "parental_education", "lunch", "test_prep"]
le = LabelEncoder()
df_enc = df.copy()
for col in cat_cols:
    df_enc[col] = le.fit_transform(df_enc[col])

features = ["gender", "parental_education", "lunch", "test_prep","reading_writing_avg"]
target   = "math_score"

X = df_enc[features]
y = df_enc[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

scaler  = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s  = scaler.transform(X_test)

#4. TRAIN MODELS

models = {
    "Linear Regression":  LinearRegression(),
    "Random Forest":      RandomForestRegressor(n_estimators=200, random_state=42),
    "Gradient Boosting":  GradientBoostingRegressor(n_estimators=200, random_state=42),
}

results, preds_dict = {}, {}
for name, model in models.items():
    Xtr = X_train_s if name == "Linear Regression" else X_train
    Xte = X_test_s  if name == "Linear Regression" else X_test
    model.fit(Xtr, y_train)
    p   = model.predict(Xte)
    rmse = np.sqrt(mean_squared_error(y_test, p))
    r2   = r2_score(y_test, p)
    results[name]   = {"RMSE": round(rmse, 3), "R²": round(r2, 4)}
    preds_dict[name] = p
    print(f"\n{name:22s}  RMSE={rmse:.3f}  R²={r2:.4f}")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/StudentsPerformance.csv")
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.rename(columns={
    "race/ethnicity":              "ethnicity",
    "parental_level_of_education": "parental_edu",
    "test_preparation_course":     "test_prep",
    "math_score":                  "math",
    "reading_score":               "reading",
    "writing_score":               "writing"
}, inplace=True)

df["avg_score"] = (df["math"] + df["reading"] + df["writing"]) / 3

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle("Factors Affecting Academic Performance", fontsize=16, fontweight="bold")
fig.patch.set_facecolor("#F7F9FC")

# 1. Gender
df.groupby("gender")["avg_score"].mean().plot(kind="bar", ax=axes[0,0], color=["#e74c3c","#3498db"], edgecolor="white", rot=0)
axes[0,0].set_title("Gender vs Avg Score"); axes[0,0].set_ylabel("Avg Score")
axes[0,0].bar_label(axes[0,0].containers[0], fmt="%.1f", padding=3)

# 2. Parental Education
df.groupby("parental_edu")["avg_score"].mean().sort_values().plot(kind="barh", ax=axes[0,1], color="#9b59b6", edgecolor="white")
axes[0,1].set_title("Parental Education vs Avg Score"); axes[0,1].set_xlabel("Avg Score")

# 3. Lunch Type
df.groupby("lunch")["avg_score"].mean().plot(kind="bar", ax=axes[1,0], color=["#e67e22","#27ae60"], edgecolor="white", rot=0)
axes[1,0].set_title("Lunch Type vs Avg Score"); axes[1,0].set_ylabel("Avg Score")
axes[1,0].bar_label(axes[1,0].containers[0], fmt="%.1f", padding=3)

# 4. Test Prep
df.groupby("test_prep")["avg_score"].mean().plot(kind="bar", ax=axes[1,1], color=["#c0392b","#16a085"], edgecolor="white", rot=0)
axes[1,1].set_title("Test Preparation vs Avg Score"); axes[1,1].set_ylabel("Avg Score")
axes[1,1].bar_label(axes[1,1].containers[0], fmt="%.1f", padding=3)

plt.tight_layout()
plt.show()

import gradio as gr
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

# Reload fresh copy to avoid double encoding
df_model = pd.read_csv("StudentsPerformance.csv")
df_model.columns = df_model.columns.str.strip().str.lower().str.replace(" ", "_")
df_model.rename(columns={
    "race/ethnicity":              "ethnicity",
    "parental_level_of_education": "parental_edu",
    "test_preparation_course":     "test_prep",
    "math_score":                  "math",
    "reading_score":               "reading",
    "writing_score":               "writing"
}, inplace=True)

# Feature Engineering
df_model["reading_writing_avg"] = (df_model["reading"] + df_model["writing"]) / 2

# Encode on fresh string data ✅
le_dict = {}
for col in ["gender", "parental_edu", "lunch", "test_prep"]:
    le = LabelEncoder()
    df_model[col] = le.fit_transform(df_model[col])
    le_dict[col] = le

# Train
model = LinearRegression()
model.fit(df_model[["gender","parental_edu","lunch","test_prep","reading_writing_avg"]], df_model["math"])

# Predict
def predict(gender, parental_edu, lunch, test_prep, reading, writing):
    score = model.predict([[
        le_dict["gender"].transform([gender])[0],
        le_dict["parental_edu"].transform([parental_edu])[0],
        le_dict["lunch"].transform([lunch])[0],
        le_dict["test_prep"].transform([test_prep])[0],
        (reading + writing) / 2
    ]])[0]
    return f"📊 Predicted Math Score: {np.clip(score, 0, 100):.1f} / 100"

# UI
gr.Interface(
    fn=predict,
    inputs=[
        gr.Dropdown(["female","male"],                       label="Gender"),
        gr.Dropdown(["high school","some high school",
                     "some college","associate's degree",
                     "bachelor's degree","master's degree"], label="Parental Education"),
        gr.Dropdown(["standard","free/reduced"],             label="Lunch Type"),
        gr.Dropdown(["completed","none"],                    label="Test Preparation"),
        gr.Slider(0, 100, value=70,                         label="Reading Score"),
        gr.Slider(0, 100, value=70,                         label="Writing Score"),
    ],
    outputs=gr.Textbox(label="📊 Prediction Result"),
    title="🎓 Student Math Score Predictor",
    description="Predicts Math Score using Linear Regression",
).launch(share=True)

